name: Check for broken links

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  link-checker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          fail: true
          args: --user-agent 'curl/7.54' --verbose --no-progress './**/*.md'
